apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    io.shyrka.erebus/archetype-name: "${artifactId}"
    io.shyrka.erebus/archetype-version: "${version}"
  name: ${crd-name.toLowerCase()}-operator