apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    io.shyrka.erebus/archetype-name: "${artifactId}"
    io.shyrka.erebus/archetype-version: "${version}"
spec:
  selector:
    matchLabels:
      app: ${crd-name.toLowerCase()}-operator
  template:
    metadata:
      labels:
        app: ${crd-name.toLowerCase()}-operator
    spec:
      containers:
      - name: ${crd-name.toLowerCase()}-operator
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30